Repository InvincibleZeal/billbook, pull requests merged in 2021-09, with the labels that each got.

#104 feat(redux): added Redux Functionality to project
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/pages/Customers/AddCustomer.js
  src/pages/Customers/ListCustomers.js
  src/pages/Inventory/AddItem.js
  src/pages/Inventory/ListItems.js
  src/pages/Invoice/CreateInvoice.js
  src/pages/Invoice/InvoiceModal.js
  src/pages/Invoice/ListInvoices.js
  src/redux/actions/index.js
  src/redux/constants/actions-types.js
  src/redux/reducers/customerReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/invoiceReducer.js
  src/redux/reducers/itemReducer.js
  src/redux/store.js
Labels: react-app

#113 test(table): add Test for table component
  src/components/Table.js
  src/components/__tests__/Table.test.js
  src/pages/Customers/ListCustomers.js
  src/pages/Inventory/ListItems.js
  src/pages/Invoice/ListInvoices.js
Labels: react-app

#106 Add unit-tests and integration tests
  .eslintrc.json
  .github/workflows/node.js.yml
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  src/components/Button.js
  src/components/Card.js
  src/components/Input.js
  src/components/Table.js
  src/components/__tests__/Button.test.js
  src/components/__tests__/Card.test.js
  src/components/__tests__/Input.test.js
  src/components/__tests__/Table.test.js
  src/customHooks/useForm.js
  src/notification/Toast.jsx
  src/pages/Customers/AddCustomer.js
  src/pages/Customers/__tests__/AddCustomer.test.js
  src/pages/Customers/__tests__/ListCustomers.test.js
  src/pages/Inventory/AddItem.js
  src/pages/Inventory/__tests__/AddItem.test.js
  src/pages/Inventory/__tests__/ListItems.test.js
  src/pages/Invoice/CreateInvoice.js
  src/pages/Invoice/__tests__/CreateInvoice.test.js
  src/pages/Invoice/__tests__/ListInvoices.test.js
  src/setupTests.js
Labels: enhancement

#129 fix(bottombar): bottom Bar overlapping fix
  src/styles/index.css
Labels: bug

#127 Github Action for Lighthouse
  .github/workflows/lighthouse.yml
  .gitignore
  .lighthouserc.json
  .vscode/settings.json
  package-lock.json
  package.json
  public/index.html
  src/styles/index.css
Labels: enhancement
