Repository InvincibleZeal/billbook, pull requests merged in 2021-08, with the labels that each got.

#53 Linting and husky configuration
  .eslintrc.json
  .husky/pre-commit
  .huskyrc.json
  .vscode/settings.json
  commitlint.config.js
  package-lock.json
  package.json
  src/App.js
  src/Common/Sidebar.js
  src/pages/Customers/AddCustomer.js
  src/pages/Customers/index.js
  src/pages/Inventory/AddItem.js
  src/pages/Inventory/index.js
  src/pages/Invoice/AddInvoice.js
  src/pages/Invoice/index.js
Labels: enhancement

#63 Feat/internationlisation
  jsconfig.json
  package-lock.json
  package.json
  src/App.js
  src/common/Navbar.jsx
  src/i18n/wrapper.js
  src/index.js
  src/languages/en.json
  src/languages/es.json
  src/pages/Customers/AddCustomer.js
  src/pages/Customers/ListCustomers.js
  src/pages/Inventory/AddItem.js
  src/pages/Inventory/ListItems.js
  src/pages/Invoice/CreateInvoice.js
  src/pages/Invoice/ListInvoices.js
  src/styles/add-invoice.css
  src/styles/index.css
Labels: react-app

#65 Feat/data dynamic
  jsconfig.json
  package-lock.json
  package.json
  src/App.js
  src/common/Navbar.jsx
  src/i18n/wrapper.js
  src/index.js
  src/languages/en.json
  src/languages/es.json
  src/pages/Customers/AddCustomer.js
  src/pages/Customers/ListCustomers.js
  src/pages/Inventory/AddItem.js
  src/pages/Inventory/ListItems.js
  src/pages/Invoice/AddItemsModal.js
  src/pages/Invoice/ChangeCustomerModal.js
  src/pages/Invoice/CreateInvoice.js
  src/pages/Invoice/ListInvoices.js
  src/styles/add-invoice.css
  src/styles/index.css
Labels: react-app

#62 Add notifications module
  .eslintrc.json
  .prettierrc
  jsconfig.json
  package-lock.json
  public/assets/img/circle-close.svg
  public/index.html
  src/App.js
  src/languages/en.json
  src/notification/NotificationContext.jsx
  src/notification/Toast.jsx
  src/notification/index.js
  src/notification/useNotification.jsx
  src/notification/withNotification.jsx
  src/pages/Customers/AddCustomer.js
  src/pages/Inventory/AddItem.js
  src/pages/Inventory/ListItems.js
  src/pages/Invoice/CreateInvoice.js
  src/styles/toast.css
Labels: react-app

#67 Bug fixes for issues in code-migration
   .lintstagedrc.json
  .stylelintrc.json
  .vscode/settings.json
  src/languages/en.json
  src/languages/es.json
  src/notification/useNotification.jsx
  src/notification/withNotification.jsx
  src/pages/Customers/AddCustomer.js
  src/pages/Customers/ListCustomers.js
  src/pages/Inventory/AddItem.js
  src/pages/Inventory/ListItems.js
  src/pages/Invoice/AddItemsModal.js
  src/pages/Invoice/ChangeCustomerModal.js
  src/pages/Invoice/CreateInvoice.js
  src/pages/Invoice/ListInvoices.js
  src/styles/add-invoice.css
  src/styles/variable.css
Labels: bug

#60 Feat/code-migration
   .lintstagedrc.json
  .eslintrc.json
  .prettierrc
  .stylelintrc.json
  .vscode/settings.json
  jsconfig.json
  package-lock.json
  package.json
  public/assets/img/circle-close.svg
  public/index.html
  src/App.js
  src/common/Navbar.jsx
  src/common/Sidebar.jsx
  src/common/withWrapper.jsx
  src/customHooks/useForm.js
  src/i18n/wrapper.js
  src/index.js
  src/languages/en.json
  src/languages/es.json
  src/notification/NotificationContext.jsx
  src/notification/Toast.jsx
  src/notification/index.js
  src/notification/useNotification.jsx
  src/notification/withNotification.jsx
  src/pages/Customers/AddCustomer.js
  src/pages/Customers/ListCustomers.js
  src/pages/Inventory/AddItem.js
  src/pages/Inventory/ListItems.js
  src/pages/Invoice/CreateInvoice.js
  src/pages/Invoice/InvoiceModal.js
  src/pages/Invoice/ListInvoices.js
  src/styles/add-customer.css
  src/styles/add-invoice.css
  src/styles/index.css
  src/styles/toast.css
  src/styles/variable.css
Labels: react-app

#85 refactor(createinvoice.js): fixed the str of the customers
  src/pages/Invoice/CreateInvoice.js
  src/pages/Invoice/InvoiceModal.js
  src/pages/Invoice/ListInvoices.js
Labels: bug, react-app

#87 feat(errorboundry): added Error Boundry to app level
  src/App.js
  src/common/ErrorBoundary.js
  src/styles/index.css
  src/utils/helper.js
Labels: enhancement, react-app

#90 Feature/axios
  src/axios/README.md
  src/axios/axios.js
  src/axios/index.js
Labels: enhancement

#91 fix(invoice): refactor to not mutate invoice state directly form invo…
  src/pages/Invoice/InvoiceModal.js
Labels: bug

#88 style(commitlint): add commitlint git-hook
  .husky/commit-msg
  .vscode/settings.json
  package.json
Labels: enhancement

#86 refactor(invoice-modal): refactor code to merge state
  src/pages/Invoice/CreateInvoice.js
  src/pages/Invoice/InvoiceModal.js
Labels: bug

#84 fix(navbar): fixed the position of the navabr
  src/App.js
  src/common/Navbar.jsx
  src/pages/Customers/AddCustomer.js
  src/pages/Customers/ListCustomers.js
  src/pages/Inventory/AddItem.js
  src/pages/Inventory/ListItems.js
  src/pages/Invoice/CreateInvoice.js
  src/pages/Invoice/ListInvoices.js
Labels: bug, react-app

#99 Disable button on Add Item and Customers page while saving
  src/languages/en.json
  src/languages/es.json
  src/pages/Customers/AddCustomer.js
  src/pages/Inventory/AddItem.js
  src/pages/Invoice/CreateInvoice.js
  src/pages/Invoice/InvoiceModal.js
  src/styles/index.css
Labels: bug, enhancement
